/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.contrato;

import accesoADatos.ContratoData;
import accesoADatos.InmuebleData;
import accesoADatos.InquilinoData;
import entidades.Contrato;
import entidades.Inmueble;
import entidades.Inquilino;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vista.menuPrincipal.MenuPrincipal;

/**
 *
 * @author Usuario
 */
public class CargaDeContrato extends javax.swing.JInternalFrame {
    private MenuPrincipal menuPrincipal;
    private ContratoData contratoData = new ContratoData();
    private InmuebleData inmuebleData = new InmuebleData();
    private InquilinoData inquilinoData = new InquilinoData();
    private int aviso = 0;
    /**
     * Creates new form CargaDeContrato
     */
    public CargaDeContrato(MenuPrincipal menuPrincipal) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        cargarComboInquilino();
        cargarComboInmueble();
        vaciarCampos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLContrato = new javax.swing.JLabel();
        jLIdContrato = new javax.swing.JLabel();
        jLInmueble = new javax.swing.JLabel();
        jLInquilino = new javax.swing.JLabel();
        jLFechaIni = new javax.swing.JLabel();
        campoBotonGuardar = new javax.swing.JButton();
        campoBotonModificar = new javax.swing.JButton();
        campoBotonEliminar = new javax.swing.JButton();
        campoIdContrato = new javax.swing.JTextField();
        campoBotonBuscar = new javax.swing.JButton();
        campoPrecioAlquiler = new javax.swing.JTextField();
        jLPrecio = new javax.swing.JLabel();
        campoCheckRenovado = new javax.swing.JCheckBox();
        jLFechaFin = new javax.swing.JLabel();
        campoBotonSalir = new javax.swing.JButton();
        campoCheckVigente = new javax.swing.JCheckBox();
        campoDateFechaFin = new com.toedter.calendar.JDateChooser();
        campoDateFechaInicio = new com.toedter.calendar.JDateChooser();
        ComboInmueble = new javax.swing.JComboBox<>();
        ComboInquilino = new javax.swing.JComboBox<>();

        jLContrato.setBackground(new java.awt.Color(255, 204, 204));
        jLContrato.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLContrato.setForeground(new java.awt.Color(255, 204, 204));
        jLContrato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLContrato.setText("Contratos");

        jLIdContrato.setText("ID Contrato");

        jLInmueble.setText("Inmueble");

        jLInquilino.setText("Inquilino");

        jLFechaIni.setText("Fecha de Inicio");

        campoBotonGuardar.setText("Guardar");
        campoBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBotonGuardarActionPerformed(evt);
            }
        });

        campoBotonModificar.setText("Modificar");
        campoBotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBotonModificarActionPerformed(evt);
            }
        });

        campoBotonEliminar.setText("Eliminar");
        campoBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBotonEliminarActionPerformed(evt);
            }
        });

        campoIdContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIdContratoKeyTyped(evt);
            }
        });

        campoBotonBuscar.setText("Buscar");
        campoBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBotonBuscarActionPerformed(evt);
            }
        });

        campoPrecioAlquiler.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPrecioAlquilerKeyTyped(evt);
            }
        });

        jLPrecio.setText("Precio Alquiler");

        campoCheckRenovado.setText("Renovado");

        jLFechaFin.setText("Fecha de Finalización");

        campoBotonSalir.setText("Salir");
        campoBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBotonSalirActionPerformed(evt);
            }
        });

        campoCheckVigente.setText("Vigente");
        campoCheckVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCheckVigenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoBotonEliminar)
                            .addComponent(campoCheckRenovado)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLFechaFin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoDateFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLInquilino)
                                .addComponent(jLFechaIni))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoDateFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(ComboInquilino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLInmueble)
                                .addComponent(jLIdContrato))
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(campoIdContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(ComboInmueble, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoBotonBuscar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(campoBotonGuardar)
                                    .addGap(272, 272, 272))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLPrecio)
                                            .addGap(49, 49, 49)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(campoCheckVigente)
                                                .addComponent(campoPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(campoBotonModificar)
                                            .addGap(99, 99, 99)))
                                    .addGap(53, 53, 53)))
                            .addComponent(campoBotonSalir))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIdContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIdContrato)
                    .addComponent(campoBotonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLInmueble)
                    .addComponent(ComboInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLInquilino)
                    .addComponent(ComboInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFechaIni))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFechaFin)
                    .addComponent(campoDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrecio)
                    .addComponent(campoPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCheckRenovado)
                    .addComponent(campoCheckVigente))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBotonEliminar)
                    .addComponent(campoBotonModificar)
                    .addComponent(campoBotonGuardar)
                    .addComponent(campoBotonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static boolean Validar(String datos) {
        return datos.matches("[a-zA-Z]*");
    }
    
    private void campoBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBotonEliminarActionPerformed
        if(campoIdContrato.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Para eliminar debe seleccionar un Id correspondiente");
        }else{
            int id = Integer.parseInt(campoIdContrato.getText());
            
            campoCheckVigente.setSelected(false);
        }
    }//GEN-LAST:event_campoBotonEliminarActionPerformed

    private void campoBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBotonSalirActionPerformed
        dispose();
        menuPrincipal.mostrarItemsEscritorio();
    }//GEN-LAST:event_campoBotonSalirActionPerformed

    private void campoCheckVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCheckVigenteActionPerformed
       
    }//GEN-LAST:event_campoCheckVigenteActionPerformed

    private void campoBotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBotonModificarActionPerformed
        
    }//GEN-LAST:event_campoBotonModificarActionPerformed

    private void campoBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBotonBuscarActionPerformed
         
      
    }//GEN-LAST:event_campoBotonBuscarActionPerformed

    private void campoBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBotonGuardarActionPerformed
         try{
              
            if(ComboInmueble.getSelectedIndex()<1 || ComboInquilino.getSelectedIndex()<1 ){
                JOptionPane.showMessageDialog(this, "No deje los campos vacíos");
            }else if(campoDateFechaFin.getDate() == null || campoDateFechaFin.getDate()== null  || campoPrecioAlquiler.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No dejar los campos Fecha Inicio, Fecha fin y precio vacíos.");
            }else{
                
                int id = Integer.parseInt(campoIdContrato.getText()); 
                Inmueble inmueble = (Inmueble) ComboInmueble.getSelectedItem();
                Inquilino inquilino = (Inquilino) ComboInquilino.getSelectedItem();
                double precio = Double.parseDouble(campoPrecioAlquiler.getText());
                LocalDate fecha1 = campoDateFechaInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                LocalDate fecha2 = campoDateFechaFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                boolean vigente = false;
                
                if(campoCheckVigente.isSelected()){
                    vigente = true;
                }
                
                Contrato contrato = new Contrato();
                
                contratoData.crearContrato(contrato);
                
                campoIdContrato.setText(contrato.getIdContrato()+"");
            }
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Para guardar un contrato debe completar todos los campos excepto Id");
        }            
    }//GEN-LAST:event_campoBotonGuardarActionPerformed

    private void campoIdContratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdContratoKeyTyped
         int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57 || key == 8;
        if (!numero) {
            evt.consume();
            aviso++;
            if (aviso == 5) {
                JOptionPane.showMessageDialog(this, "Solo se permiten numeros en este campo");
                aviso = 0;
            }
        }
    }//GEN-LAST:event_campoIdContratoKeyTyped

    private void campoPrecioAlquilerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPrecioAlquilerKeyTyped
       int key = evt.getKeyChar();
        boolean numero;
        if(campoPrecioAlquiler.getText().contains(".")){
            numero = key >= 48 && key <= 57 || key == 8; 
        }
        else{
            numero = key >= 48 && key <= 57 || key == 46 || key == 8;
        }
        if (!numero) {
            evt.consume();
            aviso++;
            if (aviso == 5) {
                JOptionPane.showMessageDialog(this, "En este campo solo puede ingresar números enteros o números decimales");
                aviso = 0;
            }
        }
    }//GEN-LAST:event_campoPrecioAlquilerKeyTyped
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Inmueble> ComboInmueble;
    private javax.swing.JComboBox<Inquilino> ComboInquilino;
    private javax.swing.JButton campoBotonBuscar;
    private javax.swing.JButton campoBotonEliminar;
    private javax.swing.JButton campoBotonGuardar;
    private javax.swing.JButton campoBotonModificar;
    private javax.swing.JButton campoBotonSalir;
    private javax.swing.JCheckBox campoCheckRenovado;
    private javax.swing.JCheckBox campoCheckVigente;
    private com.toedter.calendar.JDateChooser campoDateFechaFin;
    private com.toedter.calendar.JDateChooser campoDateFechaInicio;
    private javax.swing.JTextField campoIdContrato;
    private javax.swing.JTextField campoPrecioAlquiler;
    private javax.swing.JLabel jLContrato;
    private javax.swing.JLabel jLFechaFin;
    private javax.swing.JLabel jLFechaIni;
    private javax.swing.JLabel jLIdContrato;
    private javax.swing.JLabel jLInmueble;
    private javax.swing.JLabel jLInquilino;
    private javax.swing.JLabel jLPrecio;
    // End of variables declaration//GEN-END:variables

    private void cargarComboInquilino(){
        
        ArrayList<Inquilino> inquilinos = inquilinoData.listarinquilinos();
        
        ComboInquilino.addItem(null);
        
        for(Inquilino inquilino: inquilinos){
            ComboInquilino.addItem(inquilino);
            }    
    }

    private void cargarComboInmueble(){
        
        ArrayList<Inmueble> inmuebles = inmuebleData.listarInmuebles();
        
        ComboInmueble.addItem(null);
        
        for(Inmueble inmueble: inmuebles){
            ComboInmueble.addItem(inmueble);
            }    
    }
    
    private void vaciarCampos(){
        campoIdContrato.setText("");
        ComboInmueble.setSelectedIndex(0);
        ComboInquilino.setSelectedIndex(0);
        campoDateFechaFin.setDateFormatString("");
        campoDateFechaInicio.setDateFormatString("");
        campoCheckRenovado.setSelected(false);
        campoCheckVigente.setSelected(false);
    }

}
